from github import Github
import os

def get_pr_diff(repo_name: str, pr_number: int) -> str:
    """
    Fetches the diff of a pull request from GitHub.
    repo_name: "username/repo-name"
    """
    g = Github(os.getenv("GITHUB_TOKEN"))
    repo = g.get_repo(repo_name)
    pr = repo.get_pull(pr_number)

    # Collect all changed files and their patches
    diff_parts = []
    for file in pr.get_files():
        if file.patch:  # Some files (binary) have no patch
            diff_parts.append(f"File: {file.filename}\n{file.patch}")

    return "\n\n".join(diff_parts)


def post_pr_comment(repo_name: str, pr_number: int, result: dict) -> None:
    """
    Posts the pipeline results as a markdown comment on the PR.
    """
    g = Github(os.getenv("GITHUB_TOKEN"))
    repo = g.get_repo(repo_name)
    pr = repo.get_pull(pr_number)

    comment = _build_markdown_comment(result)
    pr.create_issue_comment(comment)
    print(f"Comment posted to PR #{pr_number}")


def _build_markdown_comment(result: dict) -> str:
    """
    Builds a formatted markdown string from pipeline results.
    """
    lines = []

    # Header
    lines.append("## 🤖 AI Code Review Report\n")
    lines.append(f"> {result['overall_summary']}\n")

    # Auto-fix warning
    if result["should_autofix"]:
        lines.append("---")
        lines.append("### ⚠️ Critical Issues Detected — Auto-fix branch will be created\n")

    # Critical issues
    if result["critical_issues"]:
        lines.append("### 🔴 Critical Issues")
        for issue in result["critical_issues"]:
            lines.append(f"- {issue}")
        lines.append("")

    # Per-agent findings tables
    agent_sections = [
        ("🔒 Security",     result["security_findings"],    result["security_summary"]),
        ("⚡ Performance",  result["performance_findings"], result["performance_summary"]),
        ("✨ Style",        result["style_findings"],       result["style_summary"]),
        ("🧪 Tests",        result["test_findings"],        result["test_summary"]),
    ]

    for title, findings, summary in agent_sections:
        if not findings:
            continue
        lines.append(f"---\n### {title}")
        lines.append(f"_{summary}_\n")
        lines.append("| Severity | Issue | Suggestion |")
        lines.append("|----------|-------|------------|")
        for f in findings:
            severity = f.get("severity", "?")
            issue = f.get("issue") or f.get("missing_test", "")
            suggestion = f.get("suggestion", "")
            # Emoji based on severity
            if severity >= 8:
                badge = f"🔴 {severity}/10"
            elif severity >= 5:
                badge = f"🟡 {severity}/10"
            else:
                badge = f"🟢 {severity}/10"
            lines.append(f"| {badge} | {issue} | {suggestion} |")
        lines.append("")

    # Conflicts resolved by debate agent
    if result["conflicts"]:
        lines.append("---\n### ⚖️ Conflicts Resolved by Debate Agent")
        lines.append("| Issue | Agent A | Agent B | Final Decision |")
        lines.append("|-------|---------|---------|----------------|")
        for c in result["conflicts"]:
            lines.append(
                f"| {c['issue']} "
                f"| {c['agent_a']}: {c['severity_a']}/10 "
                f"| {c['agent_b']}: {c['severity_b']}/10 "
                f"| **{c['final_severity']}/10** — {c['reasoning']} |"
            )
        lines.append("")

    lines.append("---")
    lines.append("_Generated by Autonomous Quality Pipeline_")

    return "\n".join(lines)


def get_file_content(repo_name: str, file_path: str, branch: str) -> str:
    """
    Fetches the raw content of a file from a specific branch.
    """
    g = Github(os.getenv("GITHUB_TOKEN"))
    repo = g.get_repo(repo_name)
    content = repo.get_contents(file_path, ref=branch)
    return content.decoded_content.decode("utf-8")


def create_autofix_branch(
    repo_name: str,
    pr_number: int,
    source_branch: str,
    fixed_files: dict  # {"filename": "fixed content"}
) -> str:
    """
    Creates a new autofix branch, commits fixed files,
    and posts a comment on the original PR.
    Returns the name of the created branch.
    """
    g = Github(os.getenv("GITHUB_TOKEN"))
    repo = g.get_repo(repo_name)

    # Create new branch from source branch
    autofix_branch_name = f"autofix/pr-{pr_number}"
    source_sha = repo.get_branch(source_branch).commit.sha

    # Check if branch already exists, delete if so
    try:
        repo.get_branch(autofix_branch_name)
        ref = repo.get_git_ref(f"heads/{autofix_branch_name}")
        ref.delete()
    except Exception:
        pass  # Branch doesn't exist yet, that's fine

    # Create the new branch
    repo.create_git_ref(
        ref=f"refs/heads/{autofix_branch_name}",
        sha=source_sha
    )

    # Commit each fixed file
    for file_path, fixed_content in fixed_files.items():
        current_file = repo.get_contents(file_path, ref=autofix_branch_name)
        repo.update_file(
            path=file_path,
            message=f"autofix: fix critical issues in {file_path}",
            content=fixed_content,
            sha=current_file.sha,
            branch=autofix_branch_name
        )

    # Post comment on original PR
    pr = repo.get_pull(pr_number)
    pr.create_issue_comment(
        f"🔧 **Auto-fix branch created:** `{autofix_branch_name}`\n\n"
        f"The pipeline automatically fixed the critical issues found in this PR.\n"
        f"Review the fixes: compare `{source_branch}` ← `{autofix_branch_name}`"
    )

    return autofix_branch_name