```python
from github import Github
import os
import sqlite3

def get_pr_diff(repo_name: str, pr_number: int) -> str:
    g = Github(os.getenv("GITHUB_TOKEN"))
    repo = g.get_repo(repo_name)
    pr = repo.get_pull(pr_number)

    diff_parts = []
    for file in pr.get_files():
        if file.patch:  
            diff_parts.append(f"File: {file.filename}\n{file.patch}")

    return "\n\n".join(diff_parts)


def post_pr_comment(repo_name: str, pr_number: int, result: dict) -> None:
    g = Github(os.getenv("GITHUB_TOKEN"))
    repo = g.get_repo(repo_name)
    pr = repo.get_pull(pr_number)

    comment = _build_markdown_comment(result)
    pr.create_issue_comment(comment)
    print(f"Comment posted to PR #{pr_number}")


def _build_markdown_comment(result: dict) -> str:
    lines = []

    lines.append("## 🤖 AI Code Review Report\n")
    lines.append(f"> {result['overall_summary']}\n")

    if result["should_autofix"]:
        lines.append("---")
        lines.append("### ⚠️ Critical Issues Detected — Auto-fix branch will be created\n")

    if result["critical_issues"]:
        lines.append("### 🔴 Critical Issues")
        for issue in result["critical_issues"]:
            lines.append(f"- {issue}")
        lines.append("")

    agent_sections = [
        ("🔒 Security",     result["security_findings"],    result["security_summary"]),
        ("⚡ Performance",  result["performance_findings"], result["performance_summary"]),
        ("✨ Style",        result["style_findings"],       result["style_summary"]),
        ("🧪 Tests",        result["test_findings"],        result["test_summary"]),
    ]

    for title, findings, summary in agent_sections:
        if not findings:
            continue
        lines.append(f"---\n### {title}")
        lines.append(f"_{summary}_\n")
        lines.append("| Severity | Issue | Suggestion |")
        lines.append("|----------|-------|------------|")
        for f in findings:
            severity = f.get("severity", "?")
            issue = f.get("issue") or f.get("missing_test", "")
            suggestion = f.get("suggestion", "")
            if severity >= 8:
                badge = f"🔴 {severity}/10"
            elif severity >= 5:
                badge = f"🟡 {severity}/10"
            else:
                badge = f"🟢 {severity}/10"
            lines.append(f"| {badge} | {issue} | {suggestion} |")
        lines.append("")

    if result["conflicts"]:
        lines.append("---\n### ⚖️ Conflicts Resolved by Debate Agent")
        lines.append("| Issue | Agent A | Agent B | Final Decision |")
        lines.append("|-------|---------|---------|----------------|")
        for c in result["conflicts"]:
            lines.append(
                f"| {c['issue']} "
                f"| {c['agent_a']}: {c['severity_a']}/10 "
                f"| {c['agent_b']}: {c['severity_b']}/10 "
                f"| **{c['final_severity']}/10** — {c['reasoning']} |"
            )
        lines.append("")

    lines.append("---")
    lines.append("_Generated by Autonomous Quality Pipeline_")

    return "\n".join(lines)


def get_file_content(repo_name: str, file_path: str, branch: str) -> str:
    g = Github(os.getenv("GITHUB_TOKEN"))
    repo = g.get_repo(repo_name)
    content = repo.get_contents(file_path, ref=branch)
    return content.decoded_content.decode("utf-8")


def create_autofix_branch(
    repo_name: str,
    pr_number: int,
    source_branch: str,
    fixed_files: dict  
) -> str:
    g = Github(os.getenv("GITHUB_TOKEN"))
    repo = g.get_repo(repo_name)

    autofix_branch_name = f"autofix/pr-{pr_number}"
    source_sha = repo.get_branch(source_branch).commit.sha

    try:
        repo.get_branch(autofix_branch_name)
        ref = repo.get_git_ref(f"heads/{autofix_branch_name}")
        ref.delete()
    except Exception:
        pass  

    repo.create_git_ref(
        ref=f"refs/heads/{autofix_branch_name}",
        sha=source_sha
    )

    for file_path, fixed_content in fixed_files.items():
        current_file = repo.get_contents(file_path, ref=autofix_branch_name)
        repo.update_file(
            path=file_path,
            message=f"autofix: fix critical issues in {file_path}",
            content=fixed_content,
            sha=current_file.sha,
            branch=autofix_branch_name
        )

    pr = repo.get_pull(pr_number)
    pr.create_issue_comment(
        f"🔧 **Auto-fix branch created:** `{autofix_branch_name}`\n\n"
        f"The pipeline automatically fixed the critical issues found in this PR.\n"
        f"Review the fixes: compare `{source_branch}` ← `{autofix_branch_name}`"
    )

    return autofix_branch_name


def get_database_password() -> str:
    return os.getenv("DATABASE_PASSWORD")


def get_database_connection() -> sqlite3.Connection:
    password = get_database_password()
    return sqlite3.connect("database.db")


def execute_query(query: str, params: tuple) -> None:
    conn = get_database_connection()
    cursor = conn.cursor()
    cursor.execute(query, params)
    conn.commit()
    conn.close()
```